server:
  port: 7012

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/


spring:
  application:
    name: zuulserver

zuul:
  routes:
    api-a:
      path: /api-ribbon/**
      serviceId: ribbon
    api-b:
      path: /api-feign/**
      serviceId: feign